import { Project } from "@/domain/project/project.entity";
import { formatDate } from "@/shared/utils/formatters";

export const mockProjects: Project[] = [
  {
    id: 1,
    name: "Website Redesign",
    description: "Update the company website with a new look.",
    createdAt: formatDate(new Date("2024-01-10")),
    totalTasks: 5,
    permissions: [],
  },
  {
    id: 2,
    name: "Mobile App Launch",
    description: "Release the new mobile application.",
    createdAt: formatDate(new Date("2024-01-15")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 3,
    name: "Marketing Campaign",
    description: "Start the summer marketing campaign.",
    createdAt: formatDate(new Date("2024-01-20")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 4,
    name: "Customer Survey",
    description: "Conduct a survey for customer feedback.",
    createdAt: formatDate(new Date("2024-01-25")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 5,
    name: "Backend Refactor",
    description: "Refactor backend services for scalability.",
    createdAt: formatDate(new Date("2024-01-30")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 6,
    name: "Security Audit",
    description: "Perform a security audit of all systems.",
    createdAt: formatDate(new Date("2024-02-01")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 7,
    name: "Data Migration",
    description: "Migrate data to the new database.",
    createdAt: formatDate(new Date("2024-02-05")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 8,
    name: "API Integration",
    description: "Integrate third-party APIs.",
    createdAt: formatDate(new Date("2024-02-10")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 9,
    name: "UI Improvements",
    description: "Enhance user interface components.",
    createdAt: formatDate(new Date("2024-02-15")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 10,
    name: "Performance Testing",
    description: "Test application performance under load.",
    createdAt: formatDate(new Date("2024-02-20")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 11,
    name: "Documentation Update",
    description: "Update project documentation.",
    createdAt: formatDate(new Date("2024-02-25")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 12,
    name: "Feature Rollout",
    description: "Roll out new features to users.",
    createdAt: formatDate(new Date("2024-03-01")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 13,
    name: "Bug Fixes",
    description: "Fix reported bugs from last release.",
    createdAt: formatDate(new Date("2024-03-05")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 14,
    name: "Analytics Setup",
    description: "Set up analytics tracking.",
    createdAt: formatDate(new Date("2024-03-10")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 15,
    name: "Team Training",
    description: "Organize training sessions for the team.",
    createdAt: formatDate(new Date("2024-03-15")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 16,
    name: "DevOps Pipeline",
    description: "Implement CI/CD pipeline.",
    createdAt: formatDate(new Date("2024-03-20")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 17,
    name: "Accessibility Review",
    description: "Review accessibility compliance.",
    createdAt: formatDate(new Date("2024-03-25")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 18,
    name: "Cloud Migration",
    description: "Migrate services to the cloud.",
    createdAt: formatDate(new Date("2024-04-01")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 19,
    name: "User Onboarding",
    description: "Improve user onboarding experience.",
    createdAt: formatDate(new Date("2024-04-05")),
    totalTasks: 0,
    permissions: [],
  },
  {
    id: 20,
    name: "Release Planning",
    description: "Plan the next major release.",
    createdAt: formatDate(new Date("2024-04-10")),
    totalTasks: 0,
    permissions: [],
  },
];
