import { Project } from "@/domain/project/project.entity";

export const mockProjects: Project[] = [
  {
    id: "1",
    // ownerId: "user1",
    name: "Разработка мобильного приложения",
    description:
      "Планирование, дизайн и разработка нового приложения для iOS и Android",
    totalTasks: 22,
  },
  {
    id: "2",
    // ownerId: "user1",
    name: "Планирование маркетинговой кампании",
    description: "Организация и запуск рекламной кампании для нового продукта",
    totalTasks: 12,
  },
  {
    id: "3",
    // ownerId: "user1",
    name: "Бюджет и финансы",
    description: "Планирование и контроль бюджета для текущих проектов",
    totalTasks: 1,
  },
  {
    id: "4",
    // ownerId: "user1",
    name: "Встречи и мероприятия",
    description: "Планирование и контроль бюджета для текущих проектов",
    totalTasks: 52,
  },
  {
    id: "5",
    // ownerId: "user2",
    name: "Разработка веб-сайта",
    description: "Создание корпоративного сайта для клиента",
    totalTasks: 18,
  },
  {
    id: "6",
    // ownerId: "user2",
    name: "Исследование рынка",
    description: "Анализ конкурентов и целевой аудитории",
    totalTasks: 7,
  },
  {
    id: "7",
    // ownerId: "user3",
    name: "Обновление документации",
    description: "Актуализация технической и пользовательской документации",
    totalTasks: 5,
  },
  {
    id: "8",
    // ownerId: "user3",
    name: "Обучение сотрудников",
    description: "Проведение тренингов по новым инструментам",
    totalTasks: 9,
  },
  {
    id: "9",
    // ownerId: "user4",
    name: "Тестирование продукта",
    description: "Проведение QA и исправление ошибок",
    totalTasks: 14,
  },
  {
    id: "10",
    // ownerId: "user4",
    name: "Запуск продукта",
    description: "Подготовка к релизу и публикация продукта",
    totalTasks: 6,
  },
  {
    id: "11",
    // ownerId: "user5",
    name: "Разработка API",
    description: "Проектирование и реализация REST API",
    totalTasks: 11,
  },
  {
    id: "12",
    // ownerId: "user5",
    name: "Миграция данных",
    description: "Перенос данных на новую платформу",
    totalTasks: 8,
  },
  {
    id: "13",
    // ownerId: "user6",
    name: "Дизайн логотипа",
    description: "Создание нового фирменного стиля",
    totalTasks: 3,
  },
  {
    id: "14",
    // ownerId: "user6",
    name: "Аналитика пользователей",
    description: "Сбор и анализ пользовательских данных",
    totalTasks: 10,
  },
];
