import { Task } from "@/domain/task/task.entity";
import { formatDate } from "@/shared/utils/formatters";

export const mockTasks: Task[] = [
  {
    id: 1,
    title:
      "Организовать вебинар с приглашенным экспертом: продюсирование, промо и пост-обработка записи",
    description: "Create wireframes for the homepage.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-01")),
    updatedAt: formatDate(new Date("2024-06-05")),
    projectId: 1,
    assigneeId: 1,
    authorId: 1,
  },
  {
    id: 2,
    title: "Еженедельный отчет по NPS",
    description: "Подготовить еженедельный отчет по NPS и рейтингу удовлетворенности клиентов",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-02")),
    updatedAt: formatDate(new Date("2024-06-06")),
    projectId: 2,
    assigneeId: 2,
    authorId: 1,
  },
  {
    id: 3,
    title: "Set up database",
    description: "Initialize PostgreSQL database.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-03")),
    updatedAt: formatDate(new Date("2024-06-07")),
    projectId: 3,
    assigneeId: 3,
    authorId: 1,
  },
  {
    id: 4,
    title: "Write unit tests",
    description: "Add tests for user service.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-04")),
    updatedAt: formatDate(new Date("2024-06-08")),
    projectId: 4,
    assigneeId: 4,
    authorId: 1,
  },
  {
    id: 5,
    title: "Configure CI/CD",
    description: "Set up GitHub Actions workflow.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-05")),
    updatedAt: formatDate(new Date("2024-06-09")),
    projectId: 5,
    assigneeId: 5,
    authorId: 1,
  },
  {
    id: 6,
    title: "Create API docs",
    description: "Document REST endpoints.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-06")),
    updatedAt: formatDate(new Date("2024-06-10")),
    projectId: 6,
    assigneeId: 6,
    authorId: 1,
  },
  {
    id: 7,
    title: "Fix bug #123",
    description: "Resolve issue with task sorting.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-07")),
    updatedAt: formatDate(new Date("2024-06-11")),
    projectId: 7,
    assigneeId: 7,
    authorId: 1,
  },
  {
    id: 8,
    title: "Update dependencies",
    description: "Upgrade npm packages.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-08")),
    updatedAt: formatDate(new Date("2024-06-12")),
    projectId: 8,
    assigneeId: 8,
    authorId: 1,
  },
  {
    id: 9,
    title: "Optimize images",
    description: "Compress homepage images.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-09")),
    updatedAt: formatDate(new Date("2024-06-13")),
    projectId: 9,
    assigneeId: 9,
    authorId: 1,
  },
  {
    id: 10,
    title: "Review PR #45",
    description: "Code review for new feature.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-10")),
    updatedAt: formatDate(new Date("2024-06-14")),
    projectId: 10,
    assigneeId: 10,
    authorId: 1,
  },
  {
    id: 11,
    title: "Set up linter",
    description: "Configure ESLint rules.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-11")),
    updatedAt: formatDate(new Date("2024-06-15")),
    projectId: 11,
    assigneeId: 11,
    authorId: 1,
  },
  {
    id: 12,
    title: "Prepare release notes",
    description: "Draft notes for v1.0 release.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-12")),
    updatedAt: formatDate(new Date("2024-06-16")),
    projectId: 12,
    assigneeId: 12,
    authorId: 1,
  },
  {
    id: 13,
    title: "Integrate payment gateway",
    description: "Add Stripe integration.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-13")),
    updatedAt: formatDate(new Date("2024-06-17")),
    projectId: 13,
    assigneeId: 13,
    authorId: 1,
  },
  {
    id: 14,
    title: "Refactor dashboard",
    description: "Improve dashboard layout.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-14")),
    updatedAt: formatDate(new Date("2024-06-18")),
    projectId: 14,
    assigneeId: 14,
    authorId: 1,
  },
  {
    id: 15,
    title: "Add notifications",
    description: "Implement push notifications.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-15")),
    updatedAt: formatDate(new Date("2024-06-19")),
    projectId: 15,
    assigneeId: 15,
    authorId: 1,
  },
  {
    id: 16,
    title: "Test mobile view",
    description: "Check responsiveness on mobile.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-16")),
    updatedAt: formatDate(new Date("2024-06-20")),
    projectId: 16,
    assigneeId: 16,
    authorId: 1,
  },
  {
    id: 17,
    title: "Update README",
    description: "Add setup instructions.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-17")),
    updatedAt: formatDate(new Date("2024-06-21")),
    projectId: 17,
    assigneeId: 17,
    authorId: 1,
  },
  {
    id: 18,
    title: "Implement search",
    description: "Add search bar to tasks.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-18")),
    updatedAt: formatDate(new Date("2024-06-22")),
    projectId: 18,
    assigneeId: 18,
    authorId: 1,
  },
  {
    id: 19,
    title: "Fix typo in UI",
    description: "Correct spelling errors.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-19")),
    updatedAt: formatDate(new Date("2024-06-23")),
    projectId: 19,
    assigneeId: 19,
    authorId: 1,
  },
  {
    id: 20,
    title: "Add user avatars",
    description: "Display avatars in task list.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-20")),
    updatedAt: formatDate(new Date("2024-06-24")),
    projectId: 20,
    assigneeId: 20,
    authorId: 1,
  },
  {
    id: 21,
    title: "Configure logging",
    description: "Set up application logging.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-21")),
    updatedAt: formatDate(new Date("2024-06-25")),
    projectId: 21,
    assigneeId: 21,
    authorId: 1,
  },
  {
    id: 22,
    title: "Deploy to staging",
    description: "Push latest build to staging.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-22")),
    updatedAt: formatDate(new Date("2024-06-26")),
    projectId: 22,
    assigneeId: 22,
    authorId: 1,
  },
  {
    id: 23,
    title: "Analyze performance",
    description: "Run Lighthouse audit.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-23")),
    updatedAt: formatDate(new Date("2024-06-27")),
    projectId: 23,
    assigneeId: 23,
    authorId: 1,
  },
  {
    id: 24,
    title: "Add dark mode",
    description: "Implement dark theme toggle.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-24")),
    updatedAt: formatDate(new Date("2024-06-28")),
    projectId: 24,
    assigneeId: 24,
    authorId: 1,
  },
  {
    id: 25,
    title: "Clean up code",
    description: "Remove unused imports.",
    statusId: Math.floor(Math.random() * 3) + 1,
    createdAt: formatDate(new Date("2024-06-25")),
    updatedAt: formatDate(new Date("2024-06-29")),
    projectId: 25,
    assigneeId: 25,
    authorId: 1,
  },
];
